### ISSUE TITLE
ReadMe?

### ISSUE THREAD

**Issue by z0oinks** [jottocraft/google-assistant#1]
Is there any sort of readme for this?

I have it open and it's like always listening to me or something and there's no way to shut it up.

Are you supposed to keep it open and push to talk or open it, say what you need, and close it?

**Comment by jottocraft** [comment]
There appears to be a bug that breaks the app after setup. Once you setup the assistant, close the app and relaunch it. Once it is initialized, an empty microphone icon should appear. When you click on it and the icon fills itself, you should start talking to the assistant, and what you are saying should be in a grey circle at the right. If you are having issues, click on the menu icon at the top-left, click on debug, terminate the sdk, then launch it in debug mode. If there's an error, post a screenshot here so I can help. (and of course make sure your mic is working)
![image](https://user-images.githubusercontent.com/11508240/35868474-7277e2a0-0b11-11e8-8e56-e576c708c03c.png)

I'll add all of this to the readme

**Comment by z0oinks** [comment]
![assistant](https://user-images.githubusercontent.com/4358525/35879521-6c419894-0b49-11e8-88fb-5ac12ccc95d4.PNG)
So my Assistant screen looks a bit different than yours. First, the microphone icon looks strange. Second, the grey bubble never appears to show what I'm saying.
If I click the microphone icon, it'll listen to what I say, respond, but then *keeps listening* and then responds to whatever random stuff I'm talking about to others.

Starting it in Debugging mode makes it behave normally, though. Clicking enter lets me say one command, it answers, and then it makes me click enter again.

**Comment by jottocraft** [comment]
In theory, that icon at the bottom of your screenshot should disappear and a microphone icon should appear when it detects the Assistant SDK (give it up to a minute to appear). In the debug menu, click terminate SDK, then click start assistant sdk. 

If it doesn't work after that, open task manager (control + shift + esc), click on More details at the bottom, click the arrow next to assistant and confirm that Python and googlesamples-assistant-pushtotalk.py appears (see the image below). Also tell me which version of the app you downloaded (x86 or x64), and confirm you are on python 3 by typing python in a command prompt so I can try to figure out what exactly isn't working.

![image](https://user-images.githubusercontent.com/11508240/35946662-863dc030-0c19-11e8-81ab-f73e1a75c5e8.png)

**Comment by z0oinks** [comment]
Task Manager looks fine, but Python is running version 2.7.14, which I guess is causing the issue. Problem is, I need Python 2.7 for another program that I'm running. Is there any way to run them side by side?

**Comment by jottocraft** [comment]
I uninstalled Python 3 and installed Python 2 to test this issue. Seems to be a bit unstable, but it works. Once you are done setting up, you will have the issue that you had. Restarting the app after setting up seemed to work for me, though. You might want to open the debug menu, click show log in setup, and then re-run setup to confirm that everything is properly configured, but if it continues to not work I don't really know what to tell you.

**Comment by z0oinks** [comment]
Weird. I uninstalled Python 2 and it worked fine, but after reinstalling it, it started doing the same thing again

Didn't see anything out of the ordinary in the logs, so not really sure what's going on

**Comment by z0oinks** [comment]
Actually I just started getting this when trying to launch the debug assistant:

`Terminating Main SDK Process (You will have to restart this app to re-enable it)
ERROR: The process "googlesamples-assistant-pushtotalk.exe" not found.
Starting the Google Assistant in debug mode...
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\googlesamples-assistant-pushtotalk.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 26, in <module>
    import grpc
  File "c:\python27\lib\site-packages\grpc\__init__.py", line 22, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: DLL load failed: %1 is not a valid Win32 application.
An error has occurred. Please screenshot or copy the contents of this entire window so it can be fixed.
Press any key to continue . . .`

**Comment by jottocraft** [comment]
Can you re-run setup to confirm that all of the modules are properly installed? I re-installed Python 2, but I'm not able to reproduce the error for some reason.

**Comment by z0oinks** [comment]
I erased the app settings and set it back up, but still get the same error

**Comment by jottocraft** [comment]
Since Python 2 doesn't seem to be working in this situation and no potential fix can be developed at this time, I'm just going to cut support for Python 2.
